"""Emit the static web UI's data file.

Writes `docs/players.js`, the data file for the static site. `docs/` is the
GitHub Pages publish directory (Settings -> Pages -> Deploy from branch,
main /docs), which is why it is not called `web/`.

The site is hand-written HTML plus one shared stylesheet — `index.html`
(the model), `about.html`, `assets/site.css`. Only the data file is generated;
no build step.

The JS recomputes value from scratch whenever the user moves a slider, so every
constant the formula needs is embedded here rather than baked into precomputed
numbers. The JS implementations of `computeWar`, `computeValue` and
`projectRating` mirror `valuation.py` exactly — if you change one, change both.

"""

from __future__ import annotations

import json

import numpy as np
import pandas as pd

from . import data, valuation

WEB_DIR = data.PROJECT_ROOT / "docs"

# All-Star rosters appear in the team box alongside real clubs
NON_TEAMS = {"SPO", "COOP"}

PROJECTION_SEASONS = [
    valuation.CURRENT_SEASON + k for k in range(valuation.PROJECTION_YEARS)
]


def team_lookup(season: int) -> dict[int, str]:
    tb = data.load("team_box", [season])
    pairs = tb[["team_id", "team_abbreviation"]].drop_duplicates()
    return {
        int(r.team_id): r.team_abbreviation
        for r in pairs.itertuples()
        if r.team_abbreviation not in NON_TEAMS
    }


def build_payload() -> dict:
    consts = json.loads((data.PROCESSED_DIR / "constants.json").read_text())
    df = pd.read_parquet(data.PROCESSED_DIR / "valuation.parquet")
    curve = valuation.load_aging_curve()
    teams = team_lookup(valuation.CURRENT_SEASON)

    schedule = {}
    for season in PROJECTION_SEASONS:
        s = valuation.cba_schedule(season)
        schedule[str(season)] = {
            "min_salary": round(s["min_salary"]),
            "max_salary": round(s["max_salary"]),
            "salary_cap": round(s["salary_cap"]),
            "dollars_per_win": valuation.dollars_per_win(consts, season),
        }

    players = []
    for r in df.sort_values("value", ascending=False).itertuples():
        players.append({
            "id": int(r.athlete_id),
            "name": r.athlete_display_name,
            "team": teams.get(int(r.team_id), "—") if not pd.isna(r.team_id) else "—",
            "pos": r.pos if isinstance(r.pos, str) else "—",
            "age": None if pd.isna(r.age) else int(r.age),
            "g": int(r.g),
            "mpg": round(float(r.mpg), 3),
            "availability": round(float(r.availability), 4),
            "projMinutes": round(float(r.proj_minutes), 2),
            "rating": round(float(r.rating), 3),
            "ratingForecast": round(float(r.rating_forecast), 3),
            "ratingSe": None if pd.isna(r.rating_se) else round(float(r.rating_se), 3),
            "oRapm": None if pd.isna(r.o_rapm) else round(float(r.o_rapm), 3),
            "dRapm": None if pd.isna(r.d_rapm) else round(float(r.d_rapm), 3),
            "prior": None if pd.isna(r.prior) else round(float(r.prior), 3),
            "source": r.rating_source,
            "salary": None if pd.isna(r.salary) else round(float(r.salary)),
            "signing": r.signing if isinstance(r.signing, str) else "—",
        })

    return {
        "generated": pd.Timestamp.utcnow().strftime("%Y-%m-%d"),
        "season": valuation.CURRENT_SEASON,
        "constants": {
            "minutes_baseline": consts["minutes_baseline"]["value"],
            "replacement_level": consts["replacement_level"]["value"],
            "points_per_win": consts["points_per_win"]["points_per_win"],
            "games_per_team": consts["cba"]["games_per_team"],
            "game_minutes": consts["cba"]["minutes_per_game"],
            "n_teams": consts["cba"]["n_teams"],
            "roster_min": consts["cba"]["roster_min"],
        },
        "schedule": schedule,
        "seasons": PROJECTION_SEASONS,
        "agingCurve": {
            "age": [int(a) for a in curve["age"]],
            "relValue": [float(v) for v in curve["rel_value"]],
        },
        "players": players,
    }


def main() -> None:
    payload = build_payload()
    WEB_DIR.mkdir(parents=True, exist_ok=True)

    js = (
        "// Generated by src/wnba_salary/export_web.py — do not edit by hand.\n"
        f"const MODEL = {json.dumps(payload, indent=2)};\n"
    )
    (WEB_DIR / "players.js").write_text(js)

    n_capped = sum(1 for p in payload["players"] if p["salary"] is not None)
    print(f"wrote {WEB_DIR / 'players.js'}")
    print(f"  {len(payload['players'])} players, {n_capped} with contracts")
    print(f"  seasons: {payload['seasons']}")


if __name__ == "__main__":
    main()
